$engine: 3
$onesync: on
name: "ESX Legacy Base (txAdmin Compatible)"
version: 1.0.4
author: "xxlbasher"

tasks:
  - action: download_github
    src: https://github.com/esx-framework/esx-legacy
    ref: main
    dest: ./tmp/esxlegacy

  - action: move_path
    src: ./tmp/esxlegacy/resources
    dest: ./resources

  - action: download_github
    src: https://github.com/esx-framework/esx-legacy-addons
    ref: main
    dest: ./tmp/addons

  - action: move_path
    src: ./tmp/addons
    dest: ./resources/[esx_addons]
